openapi: 3.0.0
info:
  title: Orders API
  version: 1.0.0
servers:
  - url: https://apigee-challenge-nz2wxjkrxa-no.a.run.app
paths:
  /orders:
    get:
      summary: Get all orders
      security:
        - basicAuth: []
      responses:
        '200':
          description: A list of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '401':
          description: Unauthorized
    post:
      summary: Create a new order
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: The created order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '401':
          description: Unauthorized
components:
  schemas:
    Order:
      type: object
      properties:
        order:
          type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
security:
  - basicAuth: []